---
output: 'out/Portfolio'

metadata:
  locale: en
  name: 'John Doe'
  date: '2015'
  description: 'Description in **Markdown**'

exampleOne: &one
  mode: 'background'
  title: 'Example one'
  src: ''
  context: 'Context'
  role: 'Role'

exampleTwo: &two
  mode: 'simple'
  title: 'Example two'
  src: ''
  context: 'Context'
  role: 'Role'

list:
  - *one
  - *two
